name: gencomp
channels:
  - nvidia
  - pytorch
  - conda-forge
  - esri
  - defaults
dependencies:
  - python=3.9
  - pip=20.3
  - cudatoolkit=11.8
  - pytorch=2.3.0
  - lightning=2.3.3
  - torchvision=0.18.1
  - numpy=1.24.4
  - omegaconf==2.3.0
  - einops==0.8.0
  - wandb==0.18.3
  - shapely==2.0.6
  - scikit-learn==1.3.1
  - drawsvg==2.4.0
  - cairosvg==2.7.1
  - webcolors==24.8.0
  - pandas==2.0.3
  - pyquaternion==0.9.9
  - matplotlib==3.9.2
  - imageio==2.36.0
  - biotite==0.34
  - py3dmol==2.4.0
