name: gencomp-test
channels:
  - nvidia
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.8.5
  - pip=20.3
  - cudatoolkit=11.7
  - pytorch=2.3.0
  - lightning=2.3.3
  - torchvision=0.18.1
  - numpy=1.24.4
  - pip:
      - omegaconf==2.3.0
      - einops==0.8.0
      - wandb==0.18.3
      - opencv-python==4.10.0.84
      - shapely==2.0.6
      - scikit-learn==1.3.1
      - drawsvg==2.4.0
      - cairosvg==2.7.1
      - webcolors==24.8.0
      - ltron==1.0.4
      - pandas==2.0.3
      - biotite==0.34