general:
  train: True
  test: False

model:
  base_learning_rate: 0.0001
  target: gencomp.diffusion.ddpm.DDPM
  params:
    linear_start: 0.0015
    linear_end: 0.0195
    log_every_t: 200
    timesteps: 1000
    image_size: 28
    channels: 1
    sample_shape:
      - 1
      - 28
      - 28
    monitor: val/loss
    model:
      target: gencomp.modules.unet.UNetModel
      params:
        image_size: 28
        in_channels: 1
        out_channels: 1
        model_channels: 64
        attention_resolutions:
        - 8
        - 4
        - 2
        channel_mult:
          - 1
          - 2
          - 4
        num_res_blocks: 2
        num_heads: 1

trainer:
  max_epochs: 1
  devices: 1
  accelerator: cpu

wandb:
  run_with_wandb: True
#  api_key_from_file: "code/wandb_api_key"
  save_top_k: 1 # save k best model weights
  # checkpoint_dir: "./code/lego/wandb_dir/ckpts"
  dirpath: "mnist_test" # where it saves the checkpoints
  params:
    project: "gencomp-mnist"
    save_dir: "./experiments/mnist"
    checkpoint_name: 'best_model'
    name: "mnist_test"

data:
  params:
     batch_size: 1
  dataset:
     target: mnist.dataset.CustomMNIST
     params:
       root: "data/mnist"
       train: True
       download: True
